# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-19 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20220619_0021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguindo',
            unique_together=set([('de', 'para')]),
        ),
    ]
