# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-19 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220619_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created',
            new_name='created_at',
        ),
    ]
